import { test, expect } from '@playwright/test';
const routes=[['/','Rompemos estructuras'],['/que-nos-inspira','Qué nos inspira'],['/proceso-transformacion','Proceso de transformación'],['/nuestra-filosofia','Nuestra filosofía'],['/clientes','Clientes'],['/clientes/ipc','IPC Pools'],['/clientes/nutriterra','Nutriterra']];
test('Las siete páginas cargan con título, contenido e imágenes',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
 for(const [route,title] of routes){await page.goto(route);await expect(page).toHaveTitle(`La Revuelta · ${title}`);await expect(page.locator('h1')).toBeVisible();await expect(page.locator('main')).toBeVisible();await page.evaluate(async()=>{const images=[...document.images];images.forEach(i=>i.loading='eager');await Promise.all(images.map(i=>i.decode().catch(()=>{})))});expect(await page.evaluate(()=>[...document.images].filter(i=>i.naturalWidth===0).map(i=>i.src))).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false)}
 expect(errors).toEqual([]);
});
test('La secuencia del personaje sigue el scroll y vuelve hacia atrás',async({page})=>{
 await page.goto('/');for(const i of [0,1,2,3,1,0]){await page.evaluate(i=>{const el=document.querySelector<HTMLElement>('.story-section')!;scrollTo({top:scrollY+el.getBoundingClientRect().top+(el.offsetHeight-innerHeight)*((i+.45)/4),behavior:'instant'})},i);await expect(page.locator('.story-navigation [aria-current="step"]')).toContainText(['Las personas','Las empresas','El encuentro','Más allá'][i]);await expect(page.locator('.story-copy[aria-hidden="false"]')).toHaveCount(1);await expect(page.locator('.story-copy[aria-hidden="false"]')).toBeVisible()}
 await page.getByRole('button',{name:'Pausar movimiento ambiente'}).click();await expect(page.getByRole('button',{name:'Reanudar movimiento ambiente'})).toBeVisible();
 await page.locator('.story-navigation').getByRole('button',{name:'04 Más allá'}).click();await expect(page.locator('.story-navigation [aria-current="step"]')).toContainText('Más allá');
});
test('Los datos de contacto de ejemplo abren un diálogo que cierra con Escape',async({page})=>{await page.goto('/');await page.locator('header').getByRole('button',{name:'Hablemos'}).click();await expect(page.locator('dialog')).toBeVisible();await expect(page.getByRole('link',{name:'Escribinos por WhatsApp'})).toHaveAttribute('href','https://wa.me/5491100000000');await expect(page.getByRole('link',{name:'hola@larevuelta.example'})).toHaveAttribute('href','mailto:hola@larevuelta.example');await page.keyboard.press('Escape');await expect(page.locator('dialog')).not.toBeVisible()});
test('Las tarjetas de inspiración expanden su contenido',async({page})=>{await page.goto('/que-nos-inspira');await page.getByRole('button',{name:'Conocer más sobre Nike'}).click();await expect(page.locator('.inspiration-card.expanded')).toContainText('Nos inspira esa convicción');await page.getByRole('button',{name:'Cerrar Nike'}).click();await expect(page.locator('.inspiration-card.expanded')).toHaveCount(0)});
test('El menú móvil navega y las siete páginas no desbordan',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');await page.getByRole('button',{name:'Abrir menú'}).click();await expect(page.getByRole('dialog',{name:'Navegación'})).toBeVisible();await page.locator('#mobile-menu').getByRole('link',{name:'Transformación'}).click();await expect(page).toHaveURL(/proceso-transformacion/);await expect(page.locator('#mobile-menu')).toHaveCount(0);for(const [route] of routes){await page.goto(route);await expect(page.locator('h1')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false)}});
test('La navegación entre casos y las etapas del proceso funcionan',async({page})=>{await page.goto('/clientes');await page.locator('.case-card').filter({hasText:'IPC Pools'}).click();await expect(page).toHaveURL(/clientes\/ipc/);await page.locator('.next-case').click();await expect(page).toHaveURL(/clientes\/nutriterra/);await page.goto('/proceso-transformacion');await page.locator('.phase-nav').getByRole('link',{name:'03 Más allá'}).click();await expect(page).toHaveURL(/#fase-3/);await expect(page.locator('#fase-3')).toBeInViewport();await page.locator('summary').click();await expect(page.locator('.process-faq')).toHaveAttribute('open','')});
test('El modo de movimiento reducido conserva las cuatro escenas',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/nuestra-filosofia');for(let i=0;i<4;i++){await page.evaluate(i=>{const el=document.querySelector<HTMLElement>('.story-section')!;scrollTo({top:scrollY+el.getBoundingClientRect().top+(el.offsetHeight-innerHeight)*((i+.45)/4),behavior:'instant'})},i);await expect(page.locator('.story-navigation [aria-current="step"]')).toContainText(['Las personas','Las empresas','El encuentro','Más allá'][i]);await expect(page.locator('.story-copy[aria-hidden="false"]')).toBeVisible()}});
