import { useEffect, useRef } from 'react';
import { ArrowDown, ArrowUpRight, MoveUpRight, Sparkle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { animate } from 'animejs';
export function HomeHero({contact}:{contact:()=>void}){
 const ref=useRef<HTMLElement>(null);
 useEffect(()=>{const root=ref.current!;if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const image=root.querySelector('.hero-picture')!;let anim:ReturnType<typeof animate>|undefined;const pointer=(e:PointerEvent)=>{anim?.pause();anim=animate(image,{translateX:(e.clientX/innerWidth-.5)*16,translateY:(e.clientY/innerHeight-.5)*10,duration:1200,ease:'out(3)'})};root.addEventListener('pointermove',pointer);return()=>{root.removeEventListener('pointermove',pointer);anim?.revert()}},[]);
 return <section className="home-hero" ref={ref}><div className="hero-picture" role="img" aria-label="Una oficina iluminada en amarillo entre edificios de una ciudad"/><div className="hero-shade"/><div className="hero-topline" data-intro><span><span className="status-dot"/> ESTRATEGIA. MARKETING. TRANSFORMACIÓN.</span><span>BUENOS AIRES · PARA EL MUNDO ↗</span></div><div className="hero-content"><div className="hero-pill" data-intro><Sparkle size={14}/> VAMOS POSTA</div><h1 data-intro>Rompemos<br/><em>estructuras.</em><br/>Redefinimos<br/><span className="outline-word">estándares.</span></h1><div className="hero-bottom-content" data-intro><p>Buscamos ayudar con <strong>marketing</strong> a los que apuestan a la creación de <strong>un mundo mejor.</strong></p><button className="button-primary" onClick={contact}>Hagamos una revuelta <ArrowUpRight size={20}/></button></div></div><div className="hero-photo-label" aria-hidden="true"><span className="crosshair">+</span><span>OTRA FORMA<br/>DE VER TU NEGOCIO</span><MoveUpRight size={22}/></div><div className="hero-footer" data-intro><a href="#enfoque" className="scroll-cue"><span><ArrowDown size={17}/></span>SCROLL PARA CAMBIAR LA PERSPECTIVA</a><Link to="/que-nos-inspira">Los que nos inspiran <ArrowUpRight size={16}/></Link></div></section>
}
export function PageHero({number,title,accent,description,image}:{number:string;title:string;accent:string;description:string;image:string}){return <section className="page-hero"><div className="page-hero-image" style={{backgroundImage:`url(${image})`}}/><div className="page-hero-shade"/><div className="page-hero-content"><div className="eyebrow" data-intro><span className="status-dot"/> LA REVUELTA / {number}</div><h1 data-intro>{title}<br/><em>{accent}</em><span className="title-star"><Sparkle/></span></h1><p data-intro>{description}</p></div><a href="#contenido" className="page-scroll" aria-label="Explorar contenido"><ArrowDown/></a></section>}
