import { useEffect, useRef, useState } from 'react';
import { Link, NavLink, useLocation } from 'react-router-dom';
import { ArrowDown, ArrowUpRight, Check, Menu, X } from 'lucide-react';
import { animate, stagger } from 'animejs';

export const navigation = [{to:'/que-nos-inspira',label:'Inspiración'},{to:'/proceso-transformacion',label:'Transformación'},{to:'/nuestra-filosofia',label:'Filosofía'},{to:'/clientes',label:'Clientes'}];
export function ArrowLink({to,children,className=''}:{to:string;children:React.ReactNode;className?:string}){return <Link to={to} className={`arrow-link ${className}`}>{children}<span><ArrowUpRight size={20}/></span></Link>}
export function ContactButton({className='',children='Hablemos',onClick}:{className?:string;children?:React.ReactNode;onClick:()=>void}){return <button className={`contact-button ${className}`} onClick={onClick}>{children}<ArrowUpRight size={19}/></button>}
export function Header({contact}:{contact:()=>void}) {
 const [open,setOpen]=useState(false);const location=useLocation();const menu=useRef<HTMLDivElement>(null);const toggle=useRef<HTMLButtonElement>(null);
 useEffect(()=>{setOpen(false)},[location.pathname]);
 useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const animation=animate(menu.current!.querySelectorAll('.menu-item'),{y:[40,0],opacity:[0,1],delay:stagger(65),duration:550,ease:'out(4)'});const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);toggle.current?.focus()}if(e.key==='Tab'){const nodes=[toggle.current!,...menu.current!.querySelectorAll<HTMLElement>('a,button')];const index=nodes.indexOf(document.activeElement as HTMLElement);if(e.shiftKey&&index<=0){e.preventDefault();nodes.at(-1)?.focus()}else if(!e.shiftKey&&index===nodes.length-1){e.preventDefault();nodes[0].focus()}}};document.addEventListener('keydown',close);menu.current?.querySelector<HTMLAnchorElement>('a')?.focus();return()=>{document.body.style.overflow=previous;animation.revert();document.removeEventListener('keydown',close)}},[open]);
 return <><a className="skip-link" href="#main">Saltar al contenido</a><header className="header"><Link to="/" className="brand" aria-label="La Revuelta, inicio"><img src="/logo.png" alt="La Revuelta"/><span>CONSULTORA DE MARKETING</span></Link><nav className="desktop-nav" aria-label="Navegación principal">{navigation.map(n=><NavLink key={n.to} to={n.to}>{n.label}</NavLink>)}</nav><div className="header-actions"><ContactButton onClick={contact}/><button ref={toggle} className="menu-toggle" onClick={()=>setOpen(!open)} aria-label={open?'Cerrar menú':'Abrir menú'} aria-expanded={open} aria-controls="mobile-menu">{open?<X/>:<Menu/>}</button></div></header>{open&&<div id="mobile-menu" className="menu-overlay" ref={menu} role="dialog" aria-modal="true" aria-label="Navegación"><nav>{[{to:'/',label:'Inicio'},...navigation].map((n,i)=><Link className="menu-item" to={n.to} key={n.to}><small>0{i+1}</small>{n.label}<ArrowUpRight/></Link>)}</nav><button className="menu-contact" onClick={()=>{setOpen(false);contact()}}>Tu próxima revuelta empieza acá <ArrowUpRight/></button></div>}</>
}
export function Footer({contact}:{contact:()=>void}){return <footer className="footer"><div className="footer-top"><Link to="/" aria-label="Inicio"><img src="/logo.png" alt="La Revuelta"/></Link><p>Marketing para los que apuestan<br/>a un mundo mejor.</p><button onClick={()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})} className="back-top" aria-label="Volver arriba"><ArrowDown/></button></div><div className="footer-bottom"><span>© {new Date().getFullYear()} La Revuelta.</span><nav aria-label="Navegación del pie">{navigation.map(n=><Link to={n.to} key={n.to}>{n.label}</Link>)}<button onClick={contact}>Contacto <ArrowUpRight size={14}/></button></nav><a href="https://www.aftercode.dev/" target="_blank" rel="noreferrer">Diseño original por Aftercode ↗</a></div></footer>}
export function CTA({contact}:{contact:()=>void}){return <section className="cta" data-reveal><div className="eyebrow"><span className="status-dot"/> LA PRÓXIMA REVUELTA PUEDE SER LA TUYA</div><div className="cta-line"><h2>Llevemos tu empresa<br/>al <em>siguiente nivel.</em></h2><button className="cta-round" onClick={contact} aria-label="Contactar con La Revuelta"><ArrowUpRight/></button></div><p>Tenés un sueño. Nosotros, la obsesión por hacerlo crecer.</p></section>}
export function ContactDialog({open,close}:{open:boolean;close:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const [copied,setCopied]=useState(false);const email=(import.meta.env.VITE_CONTACT_EMAIL as string|undefined)??'hola@larevuelta.example';const phone=(import.meta.env.VITE_WHATSAPP_PHONE as string|undefined)??'5491100000000';
 useEffect(()=>{const d=dialog.current!;if(open){d.showModal();document.body.style.overflow='hidden'}else{d.close();document.body.style.overflow=''}return()=>{document.body.style.overflow=''}},[open]);
 return <dialog ref={dialog} className="contact-dialog" onCancel={close} onClick={e=>{if(e.target===dialog.current)close()}}><button onClick={close} className="dialog-close" aria-label="Cerrar contacto"><X/></button><span className="eyebrow">HAGAMOS QUE PASE</span><h2>¿Cuál es tu<br/><em>próxima revuelta?</em></h2>{phone||email?<><p>Contanos sobre tu empresa y lo que querés transformar.</p>{phone&&<a className="button-primary" href={`https://wa.me/${phone.replace(/\D/g,'')}`} target="_blank" rel="noreferrer">Escribinos por WhatsApp <ArrowUpRight/></a>}{email&&<div className="email-contact"><a href={`mailto:${email}`}>{email}</a><button aria-label="Copiar email" onClick={async()=>{await navigator.clipboard.writeText(email);setCopied(true)}}>{copied?<Check/>:'Copiar'}</button></div>}</>:<><p>El canal de contacto de esta vista previa todavía no está habilitado.</p><Link to="/proceso-transformacion" onClick={close} className="button-primary">Conocé cómo trabajamos <ArrowUpRight/></Link></>}</dialog>
}
