import { ArrowUpRight, Plus, Minus } from 'lucide-react';
import { Link } from 'react-router-dom';
import processData from '../data/process.json';
export const phases=[{name:'Analítica',duration:'1 a 2 meses',title:'Generación de una hiperconciencia',image:'velocimetro',description:'Entendemos dónde estás. Investigamos tu negocio, tu público y tu mercado para encontrar las oportunidades que importan.',shortTitle:'Entender para transformar.',items:['Analítica interna y externa','Métricas clave del negocio','Investigación integral del mercado']},{name:'Crecimiento',duration:'6 meses a 1 año',title:'Potenciar tu negocio actual',image:'bars',description:'Con la información crítica obtenida en la fase anterior, definimos un plan práctico que se adapta a tu realidad actual.',shortTitle:'Convertir datos en acción.',items:['Tu estructura organizativa actual','Los productos o servicios que ya ofrecés','Las herramientas y nivel de desarrollo digital disponibles']},{name:'Más allá',duration:'Luego del primer año',title:'Planteo y desarrollo de nuevos desafíos',image:'rocket',description:'Tras estabilizar las necesidades críticas y orientar los esfuerzos hacia los objetivos definidos, es momento de expandir la visión de valor de tu empresa.',shortTitle:'Ir donde todavía no llegaste.',items:['Explorar nuevos mercados y segmentos','Lanzar nuevos productos o servicios','Desarrollar nuevas marcas']}];
export function ProcessPreview(){return <section className="process-preview section-pad" id="proceso"><div className="section-heading" data-reveal><div><div className="eyebrow">02 / EL PROCESO</div><h2>Tu transformación.<br/><em>Un paso más allá.</em></h2></div><Link to="/proceso-transformacion" className="text-link">Conocé el proceso completo <ArrowUpRight size={19}/></Link></div><div className="process-grid">{phases.map((p,i)=><Link to={`/proceso-transformacion#fase-${i+1}`} className="phase-card" key={p.name} data-reveal><div className="phase-card-top"><span className="phase-number">0{i+1}</span><span className="phase-duration">{p.duration}</span><ArrowUpRight size={19}/></div><div className="phase-visual"><img src={`/images/transformation/${p.image}.webp`} alt="" loading="lazy"/><div className="phase-orbit"/></div><div className="phase-card-text"><span className="eyebrow">{p.name}</span><h3>{p.shortTitle}</h3><p>{p.description}</p><ul>{p.items.map(item=><li key={item}>{item}</li>)}</ul></div></Link>)}</div></section>}
export function ContentBlocks({blocks}:{blocks:{tag:string;text:string}[]}){
 const nodes:React.ReactNode[]=[];
 for(let i=0;i<blocks.length;i++){const b=blocks[i];if(b.tag==='LI'){const items=[b.text];while(blocks[i+1]?.tag==='LI')items.push(blocks[++i].text);nodes.push(<ul key={i} className="content-list">{items.map(t=><li key={t}>{t}</li>)}</ul>)}else if(b.tag.startsWith('H')||b.text==='Entregables'||b.text.startsWith('Etapa ')||b.text==='Desarrollo de Plan de acción inmediato'||b.text.startsWith('Redefine tus')){nodes.push(<h3 key={i} className={b.text==='Entregables'?'deliverables-title':''}>{b.text}</h3>)}else{nodes.push(<p key={i} className={b.text.startsWith('En esta etapa')||b.text.startsWith('El único límite')?'editorial-note':''}>{b.text}</p>)}}
 return <>{nodes}</>
}
export function FullProcess(){return <div className="full-process section-pad" id="contenido"><nav className="phase-nav" aria-label="Etapas del proceso">{phases.map((p,i)=><a key={p.name} href={`#fase-${i+1}`}><span>0{i+1}</span>{p.name}<ArrowUpRight size={16}/></a>)}</nav>{phases.map((p,i)=><section className="process-detail" id={`fase-${i+1}`} key={p.name}><div className="process-sidebar"><span className="giant-number">0{i+1}</span><span className="eyebrow">{p.duration}</span><h2>{p.name}<em>.</em></h2><p>{p.title}</p><img src={`/images/transformation/${p.image}.webp`} alt="" loading="lazy"/></div><div className="process-detail-body"><ContentBlocks blocks={processData[i].blocks}/></div></section>)}<details className="process-faq"><summary>¿Podemos empezar con una sola etapa?<span className="faq-plus"><Plus/></span><span className="faq-minus"><Minus/></span></summary><p>El punto de partida es comprender tu empresa. En la etapa de analítica definimos las necesidades y las oportunidades para construir un plan que se adapte a tu realidad.</p></details></div>}
